services:
    php:
        build:
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
    mariadb:
        image: mariadb:10.4
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'user'
            MYSQL_DATABASE: 'db'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
